run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - golint
    - unconvert
    - dupl
    - goconst
    - gocyclo
    - misspell

linters-settings:
  gocyclo:
    min-complexity: 15
  golint:
    min-confidence: 0
  govet:
    check-shadowing: false

issues:
  exclude-use-default: false
  max-issues-per-linter: 50
  max-same-issues: 10
